DigitalSlideArchive/wsi-superpixel-guided-labeling

- README.rst
Reference some existing technology that this is based on, describe what exactly is being added.
> Add a better description to the README

- .git-blame-ignore-revs
- .gitignore
- tox.ini
- wsi_superpixel_guided_labeling/web_client/package.json
- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/itemList.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningStats.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialSuperpixels.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningSetupContainer.vue
This PR adds a new command to format client JS and Vue files (`tox -e formatclient`). Some of the dev dependencies were updated to make this work as expected.
Additionally, the existing client files have been formatted, including some manual changes like removing non-functional or superfluous code.
> Add command to format client files

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
Fixes #32 
Now, superpixel counts will change when re-labelling a superpixel. Additionally, Sets are used instead of arrays, and if two categories have the same name, they will both display in the running counts.
To reproduce the bug described in #32:
1. Open the initial labels view and label some superpixels with the initial category.
2. Create a new category
3. Label some of the previously labeled superpixels with the new category
4. Running count of the old category stays the same
To verify the fix in this PR, repeat the above steps, but in step 4, you should see the count update to reflect re-labeling.
While testing this PR, I discovered another issue where if two categories had the same name, they wouldn't show up separately in the running counts. Now, two categories can have the …
> Fix running counts of labeled superpixels

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
On the main guided labeling UI, the component that registers the hotkeys for labeling superpixels never un-registers the event listener. Since the listener is bound to the window, clicking `Retrain` and waiting until retrain was finished would double-bind the keyboard shortcuts. For example, trying to move to the next chip using the right arrow key would move two chips instead.
Now, when the component is destroyed (such as when the backbone view reloads after the retrain job is finished), the events are unregistered, and re-registered when the component is mounted again.
1. Open the active learning UI to the main guided labeling activity. Do some labeling using the keyboard shortcuts to verify that they work properly. 
2. Retrain. Keep the window open and wait for retrain to complete
3. …
> Remove hotkey listener on destroy

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningStats.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/store.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialSuperpixels.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningSetupContainer.vue
Previously, the SuperpixelClassification job provided the certainty per prediction as a straightforward confidence measurement.
Now, thanks to https://github.com/DigitalSlideArchive/ALBench/pull/48 and https://github.com/DigitalSlideArchive/superpixel-classification/pull/4, we can pick one of three certainty metrics at the start of training (confidence, margin, and negative entropy).
In order to get available metrics, we get the XML definition for the SuperpixelClassification there, and parse the document to find them. The choice is made by the user during step one of active learning. A dropdown menu has been added as part of that form.
> Enable different metrics for certainty

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
Fixes #48 
Previously, the number of previous successful superpixel classification jobs was used to determine what workflow step to load UI for. This caused problems when deleting/restarting a folder.
Now, we parse the annotation names for all of the annotations, looking for `/epoch (\d+)/i`, similar to what the superpixel classification job does itself to determine the epoch.
> Check superpixel names to determine workflow step

- README.rst
This uses a change
https://github.com/DigitalSlideArchive/digital_slide_archive/pull/267 to make setup easier.
> Mark the active learning folder with metadata.

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
Fixes #51 
Labeling chips was often incorrect, especially when the category list differed between the prediction and label annotations for the current epoch. This could be discovered in multiple ways: comparing labels in the active learning view to histomics ui, and refreshing the active learning view after making some labels.
In order to fix this, the code no longer assumes that the label categories and prediction categories line up 1:1. Steps are taken to ensure that the agreement is properly calculated on load, and label categories are used to set new values on the label annotation.
> Better bookkeeping in chip label view

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
close #46 
`_.debounce` was used to create a function that would only save annotations once every 500ms. Additionally, we always saved all current label annotations, and triggered a save incorrectly due to a vue watcher that fired more than expected.
`_.debounce` is no longer used to create a function for saving annotations. Instead, `saveLabelAnnotations` checks some state of the backbone view to determine what to do. If `isSaving === false`, then a request will be made to save annotations that are queued for save. Upon returning from the server, if there are any annotations that were queued up for save while work was being done on the server, another request will be made.
Also, now only the annotation that has its data changed will be queued for a save. If the categories change, all …
> Prevent simultaneous annotation saves

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
Fixes #35 
For the image viewer in the initial labels view, the following changes were made to increase usability of the activity.
1. Bounds are clamped: Now you can't push the image way out of bounds
2. The viewer has a border: Now it is easier to see the edge of the image viewer window
3. The viewer has a fixed height: This prevents the viewer from running right up against the bottom of the window.
> Improve usability of the initial label viewer

- wsi_superpixel_guided_labeling/web_client/main.js
- wsi_superpixel_guided_labeling/web_client/views/HeaderImageView.js
- wsi_superpixel_guided_labeling/web_client/views/HeaderView.js
For the active learning views, the buttons in the HistomicsUI toolbar don't work. This PR removes the buttons from the toolbar and changes the help URL to point to this repository, rather than HistomicsUI.
> Adjust HistomicsUI header

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
closes #58 
Require at least 2 categories to each have labels one some image in the dataset.
If the above condition is not met, display validation errors to the user explaining why the `Begin Training` button is disabled.
> Require labels before training

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/MouseAndKeyboardControls.vue
This adds a new component that contains a summary of the available mouse and keyboard controls. The component takes a prop to indicate if it is mounted in the setup or predictions step. If mounted during the setup step a few additional controls are listed (that are unavailable in the predictions step):
- The `annotations` category:
- Left-click: Label single superpixel
- Shift-left-drag: Continuously label superpixels
- Under the `Pan` category:
- Arrow keys / Shift-arrow keys / Shift-ctrl-arrow keys
- Under the `Zoom` category:
- Plus, minus / Shift-plus, shift-minus / Shift-ctrl-plus, shift-ctrl-minus
- 1 - 7: The number keys 1 - 7 will zoom to discrete zoom levels.
- Under the `Rotate` category:
- &lt;, &gt; (also . or ,) rotate the image a small amount. If shift is held down, &lt; and …
> Mouse keyboard controls

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/constants.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/store.js
This simply adds support for hotkey bindings beyond 9 categories. Zero still defaults to being the "reset" option, and 1 through 9 still represent the first 9 categories. After that the hotkeys follow the standard QWERTY keyboard layout, row by row.
I did try to research a little bit but as far as I can tell there is no "standard"/"best" hotkey priority ordering, but if I am mistaken or there are other preferences on order I am happy to make changes!
Addresses part of #70
> Add support for hotkeys beyond 9

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/constants.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/store.js
This branch adds support for user edits to hotkeys.
1. To start editing, select the pencil icon button. The view will update to be editable. Current hotkeys will not work (categories cannot be set while in edit mode).
2. To change a key binding, click the key assignment you'd like to change. Select the key or key combination you'd prefer and the current key text will be updated.
1. To accept the change, press enter.
2. To discard the change:
1. Click the selection again -OR-
2. Click the check mark to close edit mode without pressing enter -OR-
3. Select another key assignment without pressing enter
3. When you're done with the new assignments, click the check mark to exit the edit mode. Hotkeys for category selection is enabled again.
Some questions/concerns:
- Possible workflow change: …
> Allow users to edit hotkeys

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningStats.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/AnnotationOpacityControl.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
This adds an opacity slider to the setup and training steps that allows users to change the opacity of the superpixel boundaries.
https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/assets/51238406/3148758f-00fd-48dd-85ff-ee166cdb0929
> Add slider for annotation opacity

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/constants.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningMergeConfirmation.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/AnnotationOpacityControl.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/MouseAndKeyboardControls.vue
This PR addresses a handful of issues:
- Category management has now been moved to a floating dialog
- No longer requires using "previous" and "next" to move between categories. Instead categories can now be selected by clicking on their row in the table.
- On hover over a row a pencil icon is shown. Clicking the pencil will enable editing the category name. When editing is complete this can be indicated with the enter key or using the checkmark to the right of the input.
- Selecting the colored square for that row opens the dialog to change the category color. This change does remove the inline input that supports typing in the `rgba` value but this can still be entered in the pop-up dialog.
- Categories can be deleted by selecting one or more checkboxes and using the trash icon at the …
> Improved category selection

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
This PR drops the requirement for pressing the `Enter` key to accept the new hotkey. Accepted hotkeys include any single alphanumeric value either on its own or in conjunction with a modifier (`ctrl`, `shift`, `alt`).
One concern: One question that was raised was whether or not lowercase and uppercase letters are differentiated between. They are, but there is a difference between `CapsLock` and `Shift` if assigning a capital letter as the hotkey. Is this acceptable? Or do we need to prevent this/override this specific case?
As an example, this is acceptable:
```
a - category_1
shift+a - category_2
A - category_3
```
Although `Shift+a` and `CapsLock+a` produce a capital `A` each will label a chip with a different category.
Fixes #93
> Do not require "enter" for new hotkeys

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
In order to allow adding images during a training epoch without requiring immediate re-training we now ensure there are labels and predictions present for an image rather than assuming they always are.
Fixes #85
> Support new images during active learning

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue
Previously, we relied on the index of the selected prediction card to change in order to hit the code path that checked to see if the image had changed when we re-drew the selected superpixel bounds. Instead always check for updates regardless of selected index.
Fixes #86
> Always check for image update on page change

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
Occasionally the container is mounted twice but not destroyed, and this results in keydown events triggering the listener more than once.
Unfortunately I have been unable to reproduce this consistently in order to fix the real underlying issue. For now we just unregister the keydown listener before registering it. If it has not yet been registered nothing will happen, but if it has we will prevent registering it twice.
Fixes #94
> Remove keydown listener if already set

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue
Adds the current slide name to the guided labeling steps. Based on space and clutter this is currently in the film strip at the bottom of the screen but this can easily be moved.
Fixes #102
> Add slide name in guided labeling steps

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue
Wrap cards so that they are not cut off in small screens
Fixes #104
> Do not cut off film strip items on small screen

- README.rst
This ensures the latest version of the listed images are available (not just any version).
Add directions for updating just the superpixel cli image.
> Recommend using slicer-cli-image-pull

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
When in labeling mode users can select the "paint roller" setting which also toggles the "shift" modifier behavior. Make sure this modifier is updated to match the paint roller setting when a new image is rendered.
To test: toggle on "paint roller" mode, switch images, try to paint superpixels. This should work without issue after these changes.
> Sync modifier settings on image change

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
This further simplifies editing hotkeys and label names:
1. Hotkeys can now be edited with a single click. Changes are automatically accepted without further prompts/clicks. Clicking away from the text will exit the edit mode.
2. Editing label names can now also be completed by clicking outside of the input.
Fixes #103
> Simplify inputs

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningSetupContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/AnnotationOpacityControl.vue
Currently works when concurrency is 1. Needs support for queuing in the case of larger concurrency values.
> Superpixel speed improvements

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue
It is possible to occasionally end up in a situation where the annotations layer overlaps the filmstrip. I was unable to reproduce, but in @jagstein's example none of the other dialogs were covered. Bumps the z-index to match the others to avoid this issue.
Fixes #126
> Bump the z-index value for the filmstrip

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialSuperpixels.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/AnnotationOpacityControl.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/MouseAndKeyboardControls.vue
- Round all dialog borders
- Add a small bit of shadow to make all dialogs visible on white backrounds
- Remove margin on left of image in initial labeling
- Remove top margin from slide image
- ~Add shadows to review view as well. This can be easily dropped if it makes things too cluttered/unclear.~ NOTE: Review card shadows dropped for now to avoid a cluttered feel. This can be addressed in the future if there is a need.
> Styling fixes

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue
Addresses the following issues:
> Mosaic improvements

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningToolBar.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/utils.js
This PR adds support for tracking reviews. Currently the labels annotation metadata is updated to track which superpixels have been reviewed, what their new value is, who did that review, as well as the date and time of the review. On retraining the labels are updated to the reviewed values (if there has been a change).
Relies on changes in #130
> Track user reviews

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
First step of the filtering changes.
- Create two panels:
- `Organize`: contains grouping and sorting menus
- `Filtering`: contains all filtering menus
- Also adds a quick show all/hide all option to the detail information
> Refactor filtering UI

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
This branch adds support for filtering by comparison. There are three new menus now:
- Selecting an item from the first or second menu disables it in the other menu (there is at most only one review, one prediction, and one user selection per superpixel)
- If an item is selected from the first menu and a boolean operator (`matches` or `differs from`) is selected the second menu option defaults to `Any`.
- For example: `Predictions` + `matches` + `Any` returns all superpixels where the prediction matches either the user selection *or* the review (if there is one). This may need further discussion to make sure that is more helpful than confusing.
- If a second comparison selection is made then just the two selections are compared
- As an initial pass at conveying more information this also …
> Comparison filtering

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningMergeConfirmation.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/constants.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
Rather than a mix of category/class/label, use the term "label" everywhere in the UI.
Addresses the second half of #148.
> Use consistent terminology

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningToolBar.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
As it stands the badge is not really clear in its purpose and may only serve to create more confusion. If there is a need in the future we can re-introduce this with further discussion.
Fixes #149
> Drop the review count badge from the review tab

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
This will move labeled prediction chips to the end regardless of certainty.
> Sort superpixels by certainty and epoch it was labeled

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
Relies on #150 - requires rebase on master once #150 is merged in.
- Adds a new column to the labeling dialog that allows users to exclude a label from training
- Excluded labels are highlighted in red
- Exclusions are also stored in the histomics config file so that they are remembered between sessions. This would also allow users to easily modify their config file manually to update their exclusions list. If this is not the best place to save this information we could instead explore moving the list to the annotation metadata (with the review/label tracking information).
> Exclusions

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
Previously deleting or merging categories had become essentially unusable - the UI would often freeze. This adds a handful of improvements to fix this issue:
- Replace lodash functions with native JS where possible
- Only look at metadata and labels that we know might be affected
- Handle delete and merge in one loop rather than two separate loops
> Fix delete merge

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
This provides a solution to the bug introduced by having too many arguments using the spread operator. For the sake of resolving this bug this is sufficient, but these filtering and sorting functions can be further improved. I will make those changes in a follow-up PR.
> Do not use the spread operator with large lists

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
Newly added images will not have labels associated with them yet.
> Don't assume labels exist when saving annotations

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/AnnotationOpacityControl.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/utils.js
The major fix in this branch is refactoring the "synchronize" function which was doing too much for most use cases. Now the paths for updating the config file, saving metadata, and saving annotations has been split into separate pathways that can be selected depending on the use case:
- Only update the config file when a label name, label color, border opacity, or exclusion is changed.
- Only synchronize labels across annotations when the label name or label color is changed
- Only save annotations when label name or color is changed, a superpixel is painted, or review is made.
- Only update the pixelmap if a superpixel is painted, border opacity is changed, or label color is changed.
Additionally, this branch:
- Fixes the opacity slider (appeared to no longer be working correctly)
- …
> Additional speedups

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue
Previously, renaming a label would force the focus to jump back the first label. Keep the focus on the most recently added/changed label instead.
> Keep focus on last changed label

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/utils.js
This PR aims to provide an improved debounce function should handle the following:
- Wrapped functions are debounced if there is a previous call in progress
- Functions with "important" arguments are handled as a special case. A previous request is only considered to be "in progress" if it has identical arguments to the current call.
- The last call is always processed, even if it would have been debounced.
Fixes #165
> Improve debounce

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue
A zoomAndCenter method was added to the geojs map.  
I'm making the assumption you are on a recent version of the DSA so it has geojs >= 1.14 (from 2025-1-7).
> Use more efficient zoomAndCenter call

- wsi_superpixel_guided_labeling/web_client/main.js
- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/itemAndFolderList.js
- wsi_superpixel_guided_labeling/web_client/views/itemList.js
- When a folder is created:
- Look for `histomicsui_config` file (walks up the chain of parent folders until the file is found)
- If the file is found, looks for `activeLearning: true`
- If the flag is found, then we automatically create the `Annotations`, `Models`, and `Features` folders
- The exception to this is if we are *in* an `Annotations`, `Models`, or `Features` folder
- When a folder is opened:
- Look for `histomicsui_config` file (walks up the chain of parent folders until the file is found)
- If the file is found, looks for `activeLearning: true`
- If the flag is found, then make sure the `Annotations`, `Models`, and `Features` folders exist
- If the folders exist, check for any items
- If there are items and no `Active Learning` button, create and add the button
Fixes #82
> Detect active learning

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
There are now two options when the list of review superpixels should be updated:
1. In `Labeling` or `Guided` mode changed superpixels are handled one at a time and the list is updated in-place.
2. In review mode the full list is updated when filters, grouping, or sort are changed.
> Improve filter/group/sort

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
Hi,
In the AL filmstrip for labelling, the code for whether or not to disable scrolling to the next page is [here](https://github.com/DigitalSlideArchive/wsi-superpixel-guided-labeling/blob/master/wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue#L133)
It seems you can scroll the filmstrip for past the end. The problem seems to be
1) that `maxPage` has an OBO since the pagecount is 1-based instead of 0-based
2) that `maxPage` is calculated/updated in the store, but the Vue component's `maxPage` is in an object separate from the store.
This PR has one commit for each item.
Not sure if my code change for `this.maxPage = store.maxPage;` is a clean approach, but at least a start/suggestion 😅
> Filmstrip scroll

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewCard.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/constants.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/utils.js
- Fix review mode toggle sort order
- Fix some bugs with the comparison filters
- Fix comparison operator to ensure we're comparing user ids
- Do not disable the "any" option for second comparison choice
- Fix clashing component ids
- Update the `groupBy` options
- Adds the option to group by prediction or by review
- Removes the `agree/disagree` grouping option as it's too ambiguous
- Update the `sortBy` options
- Add the options to sort by predictions or reviews
- Remove the option to sort by `agree/disagree` because of ambiguity
- Add simple option to filter by labeled superpixels
- Add an "All Labels" option to the labels filter menu. Selecting the "All Labels" option selects all labels. De-selecting removes all label filters. Labels can still be selected/removed individually. The "no …
> Filtering improvements

- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
When choosing a user-specific option like "User Foo Labels" typically the word "labels" and maybe more is cut-off on the menu itself. Add a tooltip so it is clear with a quick hover what the complete selection is.
> Add tooltips to comparison filter menus

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue
- wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialSuperpixels.vue
Add an optional parameter `--feature`, with values `image` and `vector` to the interface with `SuperpixelClassification`, to tell `SuperpixelClassification` that it should create features as either images (the only implementation that was available until now) or vectors (using `MahmoodLab/UNI`).
When `SuperpixelClassification` is instead being invoked to train or predict, this parameter controls the shape of the model input and the model itself; the model for a `vector` is a simple "linear probing", whereas the model for an `image` continues to be a more complex, multi-layer model.
Also adjust an interface in HistomicsUI, so that when a user first loads an image and selects options for the superpixel construction, certainty metric, etc. they also specify the `--feature` value, which …
> ENH: Add support for (foundation model) vector-shaped features

- wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
This PR addresses a bug that we were seeing where:
- the initial labeling step would not automatically update when superpixels were available
- if you toggled images so that the superpixels were visible you would be unable to paint anything
This required refreshing the page to fix. Bisecting the commits narrowed the problem down to SHA 5ca41b7db667f3f261d53c32c83d3e1609e202b6, however the changes in this commit do not seem to obviously affect the initial labeling step. My best guess is that the additional re-render was somehow messing up the events, and this theory seemed to be supported by the fact that the attempts to paint would be caught for the image event triggers but not the annotation overlay triggers. That said, I was unable to conclusively trace how/when this was happening since …
> Grab certainty and feature choices at the same time
