DigitalSlideArchive/wsi-superpixel-guided-labeling

tox.ini, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningKeyboardShortcuts.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningStats.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/store.js
Resolves #17 
New Features:
- New component to handle keyboard shortcuts
- Displays as a collapsible card that lists available keyboard shortcuts
- Registers a window-level event listener for key presses
- Handles number key presses, left, and right arrow key presses
- New Keyboard shortcuts
- Left arrow key - previous card
- Right arrow key - next card
- Number keys 1-9 - select label for current superpixel card
- Number key 0 - reset decision for current superpixel card
=> Create new component to handle hotkeys

wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
Many of the TODO comments have corresponding issues.
=> Add clarifying code comments

README.rst
Add fields to `provision.local.yaml` example to support `Tasks collection`. Remove redundant `environment` fields from `docker-compose.override.yaml` example. Add brief `docker compose` installation instructions. Fix typos and misspellings.
=> Modify README.rst

wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/AnnotationOpacityControl.vue
Builds off of the work started in #36.
Fixes #80 and #22
=> Histomicsui config

wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStrip.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
=> Drop agree

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
=> Adjust for index offset on hotkey selection

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSetup/ActiveLearningInitialLabels.vue
Add support for images that may be missing annotations in the initial labeling step. Currently this simply disables selecting images that are missing their superpixel annotations (images added after generation has completed) in the initial labeling step. This behavior will be improved in #116.
Fixes #114
=> Allow labeling even if some images are missing annotations

wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
Save the `lastRunJobId` to the project metadata so that even on project copy we can find the last job parameters in order to retrain on the copied project.
=> Save last run id to metadata

wsi_superpixel_guided_labeling/web_client/views/vue/components/MouseAndKeyboardControls.vue
=> Remove unneccesary white space from instructions dialog

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewCard.vue
=> Ensure values do not overflow review card

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningLabeling.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
=> Add an option to toggle labels as well as predictions

wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js
Fix bug where review flags were cleared after retrain
=> Use index to grab review info from metadata

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
Extend the filtering options. Filter by:
- Slide
- Who labeled a given superpixel
- Who reviewed a given superpixel
- What label a superpixel was given
- What review a superpixel was given
Relies on #146
=> Additional filters

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearning/ActiveLearningFilmStripCard.vue
=> Make sure the labeling dialog is updated immediately

wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/AnnotationOpacityControl.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/utils.js
- Add custom debounce util function
- Improve review mode rendering speed
=> Additional speedups

wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewCard.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/utils.js
Allow reviewers to "unlabel" superpixels
=> Allow unlabeling

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue
=> Make sure we can still paint labels when predictions are shown

wsi_superpixel_guided_labeling/web_client/views/body/ActiveLearningView.js, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningGlobalContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/store.js
- Cache tile metadata
- Do not recompute list of superpixels
=> Improve caching

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
As requested by Jeff :
> Harvesting labels using the "review" task —this would be done by allowing users to filter classifications made by the model
=> Review mode filter by predictions

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue
Grouped superpixels are now stored as a map in order to preseve key order. Keys are sorted alphabetically by default. Toggling the "ascending"/"descending" option will also swap the order of the groups (if grouping is applied).
=> Apply sorting to groups as well

wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningReview/ActiveLearningReviewContainer.vue, wsi_superpixel_guided_labeling/web_client/views/vue/components/ActiveLearningSlideViewer.vue
This resolves some bugs around inserting/removing/updating superpixels in review mode when they're changed in labeling or guided mode.
=> Insertion sort bugs
